---
title: "analysis"
author: "Patrick Spauster"
date: '2023-10-13'
output: html_document
---

```{r setup, include=FALSE}

library(tidyverse)
library(readxl)
library(RSocrata)
library(sf)
library(leaflet)

knitr::opts_chunk$set(echo = TRUE)
```

```{r}

nypd_parking <- read_excel("NYC_Parking_Cleaned.xlsx", sheet = "Data_Sort")

nypd_parking_year <- nypd_parking %>% 
  pivot_longer(starts_with("20"), names_to = "year", values_to = "parking status") %>% 
  mutate(year = as.numeric(year)) %>% 
  filter(year >= 2012)

```

```{r}
crash_data <- read.socrata("https://data.cityofnewyork.us/resource/h9gi-nx95.csv?$where=crash_date > '2006-12-31T00:00:00.000'")

crash_data_sf <- crash_data %>% 
  mutate(crash_year = lubridate::year(crash_date)) %>% 
  filter(!is.na(latitude), crash_year %in% nypd_parking_year$year) %>% 
  st_as_sf(coords = c("longitude", "latitude")) %>% 
  st_set_crs(4326)
```

```{r}
nypd_parking_sf <- nypd_parking_year %>% 
  st_as_sf(coords = c("x", "y")) %>% 
  st_set_crs(4326)

nypd_parking_buffered <- nypd_parking_sf %>% 
  st_buffer(dist = 75)

```

```{r}

leaflet(options = leafletOptions(crs = leafletCRS(code = "EPSG:2263"))) %>% 
  addProviderTiles(provider = "CartoDB.Positron") %>% 
  addPolygons(data = nypd_parking_buffered,
              #color = "blue",
              fillOpacity = 0.5)

```

#get stats by year
```{r}
parking_crash_join <- nypd_parking_buffered %>% 
  st_intersection(crash_data_sf)


```


```{r}

crash_data_split <- split(crash_data_sf %>% filter(crash_year %in% nypd_parking_buffered$year), crash_data_sf$crash_year)
parking_data_split <- split(nypd_parking_buffered, nypd_parking_buffered$year)

parking_crash_joined <- map2_dfr(
  .x = crash_data_split,
  .y = parking_data_split,
  ~mutate(.y, crashes = lengths(st_intersect(.y,.x)))
)

parking_crash_joined_full <- map2_dfr(
  .x = crash_data_split,
  .y = parking_data_split,
  ~st_intersection(.y,.x))


```

```{r}

parking_crash_summary <- parking_crash_joined %>% 
  as.data.frame() %>% 
  group_by(year) %>% 
  summarize(crashes = sum(crashes)) %>% 
  mutate(geography = "near nypd parking")
  

overall_crash_summary <- crash_data_sf %>% 
  as.data.frame() %>% 
  group_by(crash_year) %>% 
  summarize(crashes = n()) %>% 
  rename(year = crash_year) %>% 
  mutate(geography = "citywide")

parking_city_sum <- bind_rows(overall_crash_summary, parking_crash_summary)
```



